query Airing($dateStart: Int, $nextDay: Int!, $getID: [Int]) {
  Page {
    airingSchedules(sort: TIME, airingAt_greater: $dateStart, airingAt_lesser: $nextDay, mediaId_in: $getID) {
      media {
        siteUrl
        format
        duration
        episodes
        title {
          english
          romaji
          native
        }
      }
      id
      episode
      airingAt
      timeUntilAiring
    }
  }
}
