query ($query: String) {
    Media (search: $query, type: ANIME, sort: SEARCH_MATCH) {
        id
        nextAiringEpisode {
            timeUntilAiring
            airingAt
            episode
        }
        description
        coverImage {
            large
            medium
        }
        title {
            romaji
            english
            native
        }
        format
        source
        genres
        id
        duration
        synonyms
        episodes
        meanScore
        startDate {
            year
            month
            day
        }
        endDate {
            year
            month
            day
        }
        bannerImage
      mediaListEntry {
        status
        progress
        score
        notes
        user {
          name
        }
      }
    }
}