query ($charName: String) {
  Character(search: $charName) {
    name {
      full
    }
    age
    description
    siteUrl
    image {
      large
    }
    bloodType
    dateOfBirth {
      year
      month
      day
    }
    gender
    favourites
    media {
      nodes {
        siteUrl
        title {
          romaji
          native
          english
        }
      }
    }
  }
}
