query ($type: MediaType, $userName: String) {
    MediaListCollection(userName: $userName, type: $type) {
        lists {
            entries {
                media {
                    id
                    title {
                        english
                    }
                    genres
                }
                score
            }
            name
        }
    }
}