query ListQuery($userId: Int) {
    User(id: $userId) {
      mediaListOptions {
        animeList {
          customLists
        }
        mangaList {
          customLists
        }
      }
    }
}