query ($query: String) { 
    Media (search: $query, type: MANGA, sort: POPULARITY_DESC) {
        id
        description
        coverImage {
            large
            medium
        }
        title {
            romaji
            english
            native
        }
        format
        chapters
        source
        synonyms
        volumes
        genres
        id
        meanScore
        startDate {
            year
            month
            day
        }
        endDate {
            year
            month
            day
        }
        bannerImage
    }
}