mutation SaveMediaListEntry($mediaId: Int, $status: MediaListStatus, $score: Float, $progress: Int) {
  SaveMediaListEntry(mediaId: $mediaId, status: $status, score: $score, progress: $progress) {
    mediaId
    media {
      bannerImage
      type
      title {
        userPreferred
      }
    }
    user {
      name
    }
    status
  }
}