import winston from "winston";
import { env } from "#env";
import type { Command, UsableInteraction } from "#structures/command";
import { t, type Static } from "elysia";
import { srcPath } from "./paths";

export type LogLevel = "error" | "warn" | "info" | "http" | "verbose" | "debug" | "silly";

export const GenericMetaSchema = t.Intersect(
  [
    t.Object({
      type: t.Literal("generic", { title: "Generic Type" }),
      command: t.Optional(t.String()),
      subcommand: t.Optional(t.String()),
      user: t.Optional(t.String()),
      userId: t.Optional(t.String()),
      guildId: t.Optional(t.String()),
    }, { title: "Generic Meta" }),
    t.Record(t.String(), t.Unknown()),
  ],
);

export const CommandMetaSchema = t.Object(
  {
    type: t.Literal("command", { title: "Command Type" }),
    command: t.String(),
    subcommand: t.Optional(t.String()),
    user: t.String(),
    userId: t.String(),
    guildId: t.Nullable(t.String()),
  },
  { title: "Command Meta", description: "Metadata emitted when a slash command completes execution" }
);

export const CommandDebugMetaSchema = t.Intersect(
  [
    t.Object({
      type: t.Literal("commandDebug", { title: "Command Debug Type" }),
      command: t.String(),
      subcommand: t.Optional(t.String()),
    }, { title: "Command Debug Meta" }),
    t.Record(t.String(), t.Unknown()),
  ],
);

export const EventMetaSchema = t.Object(
  {
    type: t.Literal("event", { title: "Event Type" }),
    name: t.String(),
    isOnce: t.Boolean(),
  },
  { title: "Event Meta" }
);

export const GraphQLMetaSchema = t.Object(
  {
    type: t.Literal("graphql", { title: "GraphQL Type" }),
    query: t.String(),
    vars: t.Record(t.String(), t.Any()),
    durationMs: t.Optional(t.Number()),
    rateLimitRemaining: t.Optional(t.Number()),
    authenticated: t.Boolean(),
  },
  { title: "GraphQL Meta" }
);

export const CheckMetaSchema = t.Object(
  {
    type: t.Literal("check", { title: "Check Type" }),
    name: t.Optional(t.String()),
    optional: t.Optional(t.Boolean()),
    purpose: t.Optional(t.String()),
    why: t.Optional(t.Unknown()),
    total: t.Optional(t.Number()),
  },
  { title: "Check Meta" }
);

export const StartupMetaSchema = t.Object(
  {
    type: t.Literal("startup", { title: "Startup Type" }),
    environment: t.Optional(t.String()),
    user: t.Optional(t.String()),
    total: t.Optional(t.Number()),
    commands: t.Optional(t.Array(t.String())),
    error: t.Optional(t.String()),
    component: t.Optional(t.String()),
  },
  { title: "Startup Meta" }
);

export const ErrorMetaSchema = t.Intersect(
  [
    t.Object(
      {
        type: t.Literal("error", { title: "Error Type" }),
        errorName: t.Optional(t.String()),
        stack: t.Optional(t.String()),
        errors: t.Optional(t.Array(t.String())),
      },
      { title: "Error Meta" }
    ),
    t.Record(t.String(), t.Unknown()),
  ]
);

export const LogMetaSchema = t.Union([
  GenericMetaSchema,
  CommandMetaSchema,
  CommandDebugMetaSchema,
  EventMetaSchema,
  GraphQLMetaSchema,
  CheckMetaSchema,
  StartupMetaSchema,
  ErrorMetaSchema,
]);

export const LogEntrySchema = t.Object({
  timestamp: t.Optional(t.String({ description: "ISO Timestamp generated by Winston" })),
  level: t.Union([
    t.Literal("error", { title: "Error" }),
    t.Literal("warn", { title: "Warn" }),
    t.Literal("info", { title: "Info" }),
    t.Literal("http", { title: "HTTP" }),
    t.Literal("verbose", { title: "Verbose" }),
    t.Literal("debug", { title: "Debug" }),
    t.Literal("silly", { title: "Silly" }),
  ]),
  message: t.String(),
  meta: t.Optional(LogMetaSchema),
});

export type LogMeta = Static<typeof LogMetaSchema>;
export type LogEntry = Static<typeof LogEntrySchema>;

const nestMetaFormat = winston.format((info) => {
  const { timestamp, level, message, meta, ...rest } = info;
  const mergedMeta = meta ? { ...meta, ...rest } : rest;

  if (Object.keys(mergedMeta).length > 0) {
    return {
      timestamp,
      level,
      message,
      meta: mergedMeta,
    };
  }

  return { timestamp, level, message };
});

class Logger {
  public logger: winston.Logger;

  constructor(filename: string) {
    this.logger = winston.createLogger({
      level: "debug",
      transports: [
        new winston.transports.File({
          filename,
          format: winston.format.combine(
            winston.format.timestamp(),
            nestMetaFormat(),
            winston.format.json()
          ),
        }),
      ],
    });

    this.logger.add(
      new winston.transports.Console({
        level: env.NODE_ENV === "development" ? "debug" : "info",
        format: winston.format.combine(
          winston.format.colorize(),
          winston.format.timestamp({ format: "YYYY-MM-DD HH:mm:ss" }),
          winston.format.printf(({ timestamp, level, message, meta, ...rest }) => {
            const combinedMeta = meta ?? rest;
            const metaStr = Object.keys(combinedMeta).length ? JSON.stringify(combinedMeta) : "";

            const timeStr = String(timestamp);
            const levelStr = String(level);
            const msgStr = String(message);

            return `${timeStr} | [${levelStr}]: ${msgStr} ${metaStr}`.trim();
          }),
        ),
      }),
    );
  }

  log(level: LogLevel, message: string, meta?: LogMeta) {
    this.logger.log(level, message, meta);
  }

  info(message: string, meta?: LogMeta) {
    this.logger.info(message, meta);
  }

  error(message: string | Error | unknown, meta?: LogMeta) {
    if (message instanceof Error) {
      const errMeta: Record<string, unknown> = {
        type: "error",
        errorName: message.name,
        stack: message.stack,
        ...meta,
      };

      if (message instanceof AggregateError) {
        errMeta.errors = message.errors.map((e) => (e instanceof Error ? e.message : String(e)));
      }

      this.logger.error(message.message || message.name, errMeta);
      return;
    }

    const logMessage = typeof message === "string" ? message : String(message);
    const finalMeta = meta ? { ...meta, type: "error" } : { type: "error" };
    this.logger.error(logMessage, finalMeta);
  }

  debug(message: string, meta?: LogMeta) {
    this.logger.debug(message, meta);
  }

  warn(message: string, meta?: LogMeta) {
    this.logger.warn(message, meta);
  }

  logCommand(command: Command, interaction: UsableInteraction) {
    if (!interaction.isChatInputCommand()) return;
    const subcommand = interaction.options.getSubcommand(false) ?? "";

    this.debug("Command executed", {
      type: "command",
      command: command.name,
      subcommand,
      user: interaction.user.tag,
      userId: interaction.user.id,
      guildId: interaction.guildId,
    });
  }
}

export default Logger;
export const logger = new Logger(srcPath("logging", "logs.json"));