import winston from "winston";
import { env } from "#env";
import type { Command, UsableInteraction } from "#structures/command";
import { t, type Static } from "elysia";
import { srcPath } from "./paths";

export type LogLevel = "error" | "warn" | "info" | "http" | "verbose" | "debug" | "silly";

export const GenericMetaSchema = t.Intersect(
  [
    t.Object({
      type: t.Literal("generic", { title: "Generic Type" }),
      command: t.Optional(t.String()),
      subcommand: t.Optional(t.String()),
      user: t.Optional(t.String()),
      userId: t.Optional(t.String()),
      guildId: t.Optional(t.String()),
    }, { title: "Generic Meta" }),
    t.Record(t.String(), t.Unknown()),
  ],
);

export const CommandMetaSchema = t.Object(
  {
    type: t.Literal("command", { title: "Command Type" }),
    command: t.String(),
    subcommand: t.Optional(t.String()),
    user: t.String(),
    userId: t.String(),
    guildId: t.Nullable(t.String()),
  },
  { title: "Command Meta", description: "Metadata emitted when a slash command completes execution" }
);

export const CommandDebugMetaSchema = t.Intersect(
  [
    t.Object({
      type: t.Literal("commandDebug", { title: "Command Debug Type" }),
      command: t.String(),
      subcommand: t.Optional(t.String()),
    }, { title: "Command Debug Meta" }),
    t.Record(t.String(), t.Unknown()),
  ],
);

export const EventMetaSchema = t.Object(
  {
    type: t.Literal("event", { title: "Event Type" }),
    name: t.String(),
    isOnce: t.Boolean(),
  },
  { title: "Event Meta" }
);

export const GraphQLMetaSchema = t.Object(
  {
    type: t.Literal("graphql", { title: "GraphQL Type" }),
    query: t.String(),
    vars: t.Record(t.String(), t.Any()),
    durationMs: t.Optional(t.Number()),
    rateLimitRemaining: t.Optional(t.Number()),
    authenticated: t.Boolean(),
  },
  { title: "GraphQL Meta" }
);

export const CheckMetaSchema = t.Object(
  {
    type: t.Literal("check", { title: "Check Type" }),
    name: t.Optional(t.String()),
    optional: t.Optional(t.Boolean()),
    purpose: t.Optional(t.String()),
    why: t.Optional(t.Unknown()),
    total: t.Optional(t.Number()),
  },
  { title: "Check Meta" }
);

export const StartupMetaSchema = t.Object(
  {
    type: t.Literal("startup", { title: "Startup Type" }),
    environment: t.Optional(t.String()),
    user: t.Optional(t.String()),
    total: t.Optional(t.Number()),
    commands: t.Optional(t.Array(t.String())),
    error: t.Optional(t.String()),
    component: t.Optional(t.String()),
  },
  { title: "Startup Meta" }
);

export const LogMetaSchema = t.Union([
  GenericMetaSchema,
  CommandMetaSchema,
  CommandDebugMetaSchema,
  EventMetaSchema,
  GraphQLMetaSchema,
  CheckMetaSchema,
  StartupMetaSchema,
]);

export const LogEntrySchema = t.Intersect([
  t.Object({
    timestamp: t.Optional(t.String({ description: "ISO Timestamp generated by Winston" })),
    level: t.Union([
      t.Literal("error", { title: "Error" }),
      t.Literal("warn", { title: "Warn" }),
      t.Literal("info", { title: "Info" }),
      t.Literal("http", { title: "HTTP" }),
      t.Literal("verbose", { title: "Verbose" }),
      t.Literal("debug", { title: "Debug" }),
      t.Literal("silly", { title: "Silly" }),
    ]),
    message: t.String(),
  }),
  t.Partial(LogMetaSchema),
]);


export type CommandMeta = Static<typeof CommandMetaSchema>;
export type GenericMeta = Static<typeof GenericMetaSchema>;
export type CommandDebugMeta = Static<typeof CommandDebugMetaSchema>;
export type EventMeta = Static<typeof EventMetaSchema>;
export type GraphQLMeta = Static<typeof GraphQLMetaSchema>;
export type CheckMeta = Static<typeof CheckMetaSchema>;
export type StartupMeta = Static<typeof StartupMetaSchema>;

export type LogMeta = Static<typeof LogMetaSchema>;

export type LogEntry = Static<typeof LogEntrySchema>;

class Logger {
  public logger: winston.Logger;

  constructor(filename: string) {
    this.logger = winston.createLogger({
      level: "debug",
      transports: [
        new winston.transports.File({
          filename,
          format: winston.format.combine(winston.format.timestamp(), winston.format.json()),
        }),
      ],
    });

    this.logger.add(
      new winston.transports.Console({
        level: env().NODE_ENV === "development" ? "debug" : "info",
        format: winston.format.combine(
          winston.format.colorize(),
          winston.format.timestamp({ format: "YYYY-MM-DD HH:mm:ss" }),
          winston.format.printf(({ timestamp, level, message, ...meta }) => {
            const metaStr = Object.keys(meta).length ? JSON.stringify(meta) : "";
            return `${timestamp} | [${level}]: ${message} ${metaStr}`;
          }),
        ),
      }),
    );
  }

  log(level: LogLevel, message: string, meta?: LogMeta) {
    this.logger.log(level, message, meta);
  }

  info(message: string, meta?: LogMeta) {
    this.logger.info(message, meta);
  }

  error(message: string, meta?: LogMeta) {
    this.logger.error(message, meta);
  }

  debug(message: string, meta?: LogMeta) {
    this.logger.debug(message, meta);
  }

  logCommand(command: Command, interaction: UsableInteraction) {
    if (!interaction.isChatInputCommand()) return;
    const subcommand = interaction.options.getSubcommand(false) ?? "";

    this.debug("Command executed", {
      type: "command",
      command: command.name,
      subcommand,
      user: interaction.user.tag,
      userId: interaction.user.id,
      guildId: interaction.guildId,
    });
  }
}

export default Logger;
export const logger = new Logger(srcPath("logging", "logs.json"));