query Activity($userid: Int) {
  Activity(userId: $userid, sort: ID_DESC, type_not: MESSAGE) {
    __typename
    ... on TextActivity {
      text
      siteUrl
      createdAt
      user {
        name
        avatar {
          large
        }
      }
      likes {
        name
      }
      likeCount
      replyCount
    }
    ... on ListActivity {
      user {
        name
        avatar {
          large
        }
      }
      likeCount
      replyCount
      status
      progress
      media {
        siteUrl
        bannerImage
        title {
          romaji
          native
          english
        }
        coverImage {
          extraLarge
          large
          medium
        }
      }
      createdAt
      siteUrl
      likes {
        name
      }
    }
    ... on MessageActivity {
      createdAt
    }
  }
}
