query GetMediaCollection($type: MediaType, $userName: String, $userId: Int) {
  MediaListCollection(type: $type, userName: $userName, userId: $userId) {
    lists {
      entries {
        media {
          id
          title {
            english
          }
          genres
        }
        score
        status
        notes
        progress
      }
      name
    }
    user {
      name
      mediaListOptions {
        scoreFormat
      }
    }
  }
}