query User($username: String, $userid: Int) {
    User(name: $username, id: $userid) {
        id
        name
        avatar {
            large
            medium
        }
        bannerImage
        siteUrl
        createdAt
        options {
            profileColor
        }
        statistics {
            anime {
                count
                meanScore
                standardDeviation
                minutesWatched
                episodesWatched
                genres(limit: 1, sort: [COUNT_DESC]) {
                    genre
                    count
                }
                formats(limit: 1, sort: [COUNT_DESC]) {
                    format
                    count
                }
            }
            manga {
                count
                meanScore
                standardDeviation
                chaptersRead
                volumesRead
                genres(limit: 1, sort: [COUNT_DESC]) {
                    genre
                    count
                }
            }
        }
    }
}
