query Viewer {
    Viewer {
        statistics {
            anime {
                count
            }
            manga {
                count
            }
        }
        id
        name
    }
}
